[package]
name = "manatan-documentation"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
pulldown-cmark = "0.13"
tokio = { version = "1.47", features = ["macros", "rt-multi-thread", "net"] }
